[package]
name = "criterion_bench"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = {version = "0.3", features = ["html_reports"]}

[[bench]]
name = "euler1_benchmark"
harness = false
