name: Run Rust Benchmarks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions/setup-rust@v2  # Using the correct action version
      with:
        rust-version: stable  # You can specify a version if needed

    - name: Install dependencies
      run: cargo install criterion

    - name: Run benchmarks
      run: cargo bench
