name: Run Rust Benchmarks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable]  # You can specify other Rust versions if needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: ${{ matrix.rust }}  # Use the matrix for different Rust versions

    - name: Install dependencies
      run: cargo install criterion

    - name: Run benchmarks
      run: cargo bench
