name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions/setup-rust@v2  # Ensure Rust is set up
      with:
        rust-version: stable
    - name: Build
      run: cargo build --verbose
    - name: Run benchmarks
      run: cargo bench --verbose  # Run the benchmarks here
